[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
# Add your RPC endpoints here if needed
# mainnet = "${MAINNET_RPC_URL}"

[etherscan]
# Add your Etherscan API key here if needed
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
